export const TYPES = {
  SET_SELECTED_USER: "SET_SELECTED_USER",
  ADD_USER: "ADD_USER",
  EDIT_USER: "EDIT_USER",
  DELETE_USER: "DELETE_USER",
  SET_SELECTED_POSITION: "SET_SELECTED_POSITION",
  ADD_POSITION: "ADD_POSITION",
  EDIT_POSITION: "EDIT_POSITION",
  DELETE_POSITION: "DELETE_POSITION",
};
